version: '3.8'

services:
    
  ml_api:
    build:
      dockerfile: ./3_ML
      context: afklm_ml_api_Dockerfile
    container_name: dst_de_airlines_ml_api
    ports:
      - "8001:8001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  mongodb:
    image: mongo:7.0
    container_name: dst_de_airlines_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: airlines
      MONGO_INITDB_ROOT_PASSWORD: airlines
    volumes:
      - ./2_bdd_afklm_volumes:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  mongodb_api:
    build:
      context: ./2_bdd/MongoDb/dst_de_airlines_api/
      dockerfile: Dockerfile
    container_name: dst_de_airlines_mongodb_api
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://airlines:airlines@host.docker.internal:27017/airlines?authSource=admin
      - DATABASE_NAME=airlines
      - FOLDER_PATH=/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    

  postgres:
    container_name: dst_de_airlines_postgres
    build:
      context: ./2_bdd/Postgre/
      dockerfile: postgres_Dockerfile
    
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: datascientest
      POSTGRES_DB: dst_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s      
    volumes:
      - ./2_bdd/Postgre/postgres_volume:/var/lib/postgresql/data
      - ./2_bdd/Postgre/mongodb_dump:/var/lib/postgresql/data/mongodb_dump


  pgadmin:
    container_name: dst_de_airlines_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: daniel@datascientest.com
      PGADMIN_DEFAULT_PASSWORD: data_engineer
    ports:
      - "5050:80"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 10s
      start_period: 160s
      retries: 3
