version: "3.3"

services:
 api:               
    build: .
    container_name: afklm_api
    ports:
      - "7374:7374"
    environment:
      - API_DST_AIRLINES_URL=http://host.docker.internal:8000/
      - DATA_INPUT=../data_input/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
