
INSERT INTO delay (flight_id, flightLegs_irregularity_delayDuration, flightLegs_irregularity_delayInfo_delayReasonPublicLong, flightLegs_irregularity_delayInfo_delayReasonPublicShort)
SELECT distinct CONCAT (id, flightLegs_depInfo_airport_code,flightLegs_arrInfo_airport_code), flightLegs_irregularity_delayDuration, flightLegs_irregularity_delayInfo_delayReasonPublicLong, flightLegs_irregularity_delayInfo_delayReasonPublicShort
FROM mongodb;

INSERT INTO arrival_airport (flight_id, flightLegs_arrInfo_airport_code, flightLegs_arrInfo_airport_places_arrivalPositionTerminal, flightLegs_arrInfo_times_scheduled_date, flightLegs_arrInfo_times_scheduled_time, flightLegs_arrInfo_times_scheduled_year, flightLegs_arrInfo_times_scheduled_month, flightLegs_arrInfo_times_scheduled_day, flightLegs_arrInfo_times_scheduled_hour, flightLegs_arrInfo_times_scheduled_minute, flightLegs_arrInfo_times_scheduled_timezone, flightLegs_arrInfo_times_number_week)
SELECT distinct CONCAT (id, flightLegs_depInfo_airport_code,flightLegs_arrInfo_airport_code), flightLegs_arrInfo_airport_code, flightLegs_arrInfo_airport_places_arrivalPositionTerminal, CAST (SUBSTRING (flightLegs_arrInfo_times_scheduled, 0, 11) AS DATE) date, CAST (SUBSTRING (flightLegs_arrInfo_times_scheduled, 12, 5) AS time) time, CAST (SUBSTRING (flightLegs_arrInfo_times_scheduled, 1, 4) AS INTEGER), CAST (SUBSTRING (flightLegs_arrInfo_times_scheduled, 6, 2) AS INTEGER), CAST (SUBSTRING (flightLegs_arrInfo_times_scheduled, 9, 2) AS INTEGER), CAST (SUBSTRING (flightLegs_arrInfo_times_scheduled, 12, 2) AS INTEGER), CAST (SUBSTRING (flightLegs_arrInfo_times_scheduled, 15, 2) AS INTEGER), SUBSTRING (flightLegs_arrInfo_times_scheduled, 24, 6), EXTRACT(WEEK FROM TO_TIMESTAMP(SUBSTRING (flightLegs_arrInfo_times_scheduled, 1, 10), 'YYYY/MM/DD/HH24:MI:ss'))
FROM mongodb;

INSERT INTO departure_airport (flight_id, flightLegs_depInfo_airport_code, flightLegs_depInfo_airport_places_depPosTerm_boardingTerminal, flightLegs_depInfo_airport_places_depPosTerm_gateNumber, flightLegs_depInfo_times_scheduled_date, flightLegs_depInfo_times_scheduled_time, flightLegs_depInfo_times_scheduled_year, flightLegs_depInfo_times_scheduled_month, flightLegs_depInfo_times_scheduled_day, flightLegs_depInfo_times_scheduled_hour, flightLegs_depInfo_times_scheduled_minute, flightLegs_depInfo_times_scheduled_timezone, flightLegs_depInfo_times_number_week)
SELECT distinct CONCAT (id, flightLegs_depInfo_airport_code,flightLegs_arrInfo_airport_code), flightLegs_depInfo_airport_code, flightLegs_depInfo_airport_places_depPosTerm_boardingTerminal, flightLegs_depInfo_airport_places_depPosTerm_gateNumber, CAST (SUBSTRING (flightLegs_depInfo_times_scheduled, 0, 11) AS DATE) date, CAST (SUBSTRING (flightLegs_depInfo_times_scheduled, 12, 5) AS time) time, CAST (SUBSTRING (flightLegs_depInfo_times_scheduled, 1, 4) AS INTEGER), CAST (SUBSTRING (flightLegs_depInfo_times_scheduled, 6, 2) AS INTEGER), CAST (SUBSTRING (flightLegs_depInfo_times_scheduled, 9, 2) AS INTEGER), CAST (SUBSTRING (flightLegs_depInfo_times_scheduled, 12, 2) AS INTEGER), CAST (SUBSTRING (flightLegs_depInfo_times_scheduled, 15, 2) AS INTEGER), SUBSTRING (flightLegs_depInfo_times_scheduled, 24, 6), EXTRACT(WEEK FROM TO_TIMESTAMP(SUBSTRING (flightLegs_depInfo_times_scheduled, 1, 10), 'YYYY/MM/DD/HH24:MI:ss')) 
FROM mongodb;

INSERT INTO flight (flight_id, flightNumber, airline_code, airline_name, flightStatusPublic, flightLegs_aircraft_typeCode, flightLegs_scheduledFlightDuration, flightLegs_serviceType, flightLegs_aircraft_ownerAirlineCode, flightLegs_status, flightLegs_serviceTypeName, flightLegs_publishedStatus, flightLegs_legStatusPublic, flightLegs_statusName, delay_status)
SELECT distinct CONCAT (id, flightLegs_depInfo_airport_code,flightLegs_arrInfo_airport_code), CAST (flightNumber AS INTEGER)flightNumber, airline_code, airline_name, flightStatusPublic, flightLegs_aircraft_typeCode, flightLegs_scheduledFlightDuration, flightLegs_serviceType, flightLegs_aircraft_ownerAirlineCode, flightLegs_status, flightLegs_serviceTypeName, flightLegs_publishedStatus, flightLegs_legStatusPublic, flightLegs_statusName,
CASE
	WHEN flightLegs_irregularity_delayDuration isnull THEN false
	ELSE true END 
FROM mongodb;


